version: "3.9"

services:
    puppet-watcher:
        build: .
        container_name: puppet-watcher
        restart: unless-stopped
        environment:
            TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
            TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
            CHECK_EVERY_SECONDS: "300"  # проверять каждые 5 минут
            SEEN_FILE: "/data/seen.json"
        volumes:
            - ./data:/data
        tty: true
